name: Evaluate MDI
on: [push, workflow_dispatch]

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  sim-bib:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
          testing: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Docker Container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/muoncollidersoft/mucoll-sim:master
          run: |
            echo "Setup MuC software stack"
            source /etc/profile.d/aliases.sh
            setup_mucoll
            ddsim --version > /github/workspace/ddsim_version.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tracker-occupancies
          path: ${{ github.workspace }}/*.txt
          retention-days: 7
          overwrite: true
          compression-level: 9
